global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: housing-api
    static_configs:
      - targets: ["housing-api:8000"]
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: retraining-service
    static_configs:
      - targets: ["retraining-service:8002"]
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: mlflow
    static_configs:
      - targets: ["mlflow:5000"]
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

